import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Tile from "../components/Tile";
import {useEffect, useState} from "react";
import axios from "axios";
import data from '../../assignment-assets/data.json'


const Home: NextPage = () => {
    const [tiles, setTiles] = useState([]);

    useEffect(() => {
        axios.get('/api/tiles').then(res => setTiles(res.data))
    }, [])
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div>
                    <h1>{data["hero-1"].title}</h1>
                    <p>{data["hero-1"].description}</p>
                </div>
                <section style={{display: 'flex flex-wrap'}}>
                    {tiles && tiles.map((t, i) => <Tile tile={t} key={i}/>)}
                </section>
                <div className='banner'>
                    <img src={data.banner.image}/>
                    <div style={{width: '25%'}}>
                        <p>{data.banner.author}</p>
                        <p>{data.banner.description}</p>
                    </div>
                </div>

                <img className='full-w-image' src='/images/image-full-width.png'/>
                <div style={{display: 'flex'}}>
                    <div className='info-box'>
                        {data.imagetext.title}
                    </div>
                    <img style={{zIndex: 4}} src='/images/text-media-right.png'/>
                </div>
            </main>
            <footer className='footer'>
                <div>
                    <p>PULL REQUEST <br/>Don’t be shy to commit
                    </p>
                </div>
                <Image src="/logo.svg" alt="Rommel logo" width={73} height={92}/>
            </footer>
        </div>
    )
}

export default Home;
